name: Rust

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  windows_stable:
    runs-on: windows-latest
    steps:
    - name: Ninja Install
      run: pip install ninja
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -j 2 --verbose
    - name: Run tests
      run: cargo test -j 2 --verbose
  linux_stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -j 2 --verbose
    - name: Run tests
      run: cargo test -j 2 --verbose
  macos_stable:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -j 3 --verbose
    - name: Run tests
      run: cargo test -j 3 --verbose
